using Mutagen.Bethesda;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Aspects;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace Hephaestus_reimagined
{
    public class Program
    {
        static Lazy<Settings> _settings = null!;
        public static Settings settings => _settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline
                .Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "Hephaestus.esp")
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .Run(args);
        }

        private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.WriteLine(string.Empty);
            Console.WriteLine("=================================================");
            Console.WriteLine("Building caches...");

            // Pre-build tempering COBJ cache: item FormKey → temper COBJs
            var temperCOBJsCache = new Dictionary<FormKey, List<IConstructibleObjectGetter>>();
            foreach (var cobj in state.LoadOrder.PriorityOrder.ConstructibleObject().WinningOverrides())
            {
                if (
                    cobj.WorkbenchKeyword.FormKey != Skyrim.Keyword.CraftingSmithingArmorTable.FormKey
                    && cobj.WorkbenchKeyword.FormKey != Skyrim.Keyword.CraftingSmithingSharpeningWheel.FormKey
                )
                    continue;
                var key = cobj.CreatedObject.FormKey;
                if (key.IsNull) continue;
                if (!temperCOBJsCache.TryGetValue(key, out var list))
                {
                    list = new List<IConstructibleObjectGetter>();
                    temperCOBJsCache[key] = list;
                }
                list.Add(cobj);
            }

            // Pre-build reverse LVLI cache: item FormKey → leveled lists that reference it
            var lvliCache = new Dictionary<FormKey, List<ILeveledItemGetter>>();
            foreach (var lvli in state.LoadOrder.PriorityOrder.LeveledItem().WinningOverrides())
            {
                if (lvli.Entries == null) continue;
                foreach (var entry in lvli.Entries)
                {
                    var refKey = entry.Data?.Reference.FormKey ?? FormKey.Null;
                    if (refKey == FormKey.Null) continue;
                    if (!lvliCache.TryGetValue(refKey, out var lvliList))
                    {
                        lvliList = new List<ILeveledItemGetter>();
                        lvliCache[refKey] = lvliList;
                    }
                    if (!lvliList.Contains(lvli))
                        lvliList.Add(lvli);
                }
            }

            Console.WriteLine("Finding craftable items with tempering recipes...");

            // Enumerate crafting COBJs: items must have a matching bench AND a tempering recipe
            var itemCOBJs = new Dictionary<FormKey, List<FormKey>>();
            foreach (var cobj in state.LoadOrder.PriorityOrder.ConstructibleObject().WinningOverrides())
            {
                if (
                    cobj.Items == null
                    || !settings.BenchSettings.Any(e => e.BenchKeyword.FormKey == cobj.WorkbenchKeyword.FormKey)
                    || !cobj.CreatedObject.TryResolve(state.LinkCache, out var createdItem)
                )
                    continue;

                if (settings.itemBlacklist.Contains(createdItem))
                    continue;

                // Only track items that can be tempered
                if (!temperCOBJsCache.ContainsKey(createdItem.FormKey))
                    continue;

                if (!itemCOBJs.ContainsKey(createdItem.FormKey))
                    itemCOBJs[createdItem.FormKey] = new List<FormKey>();
                itemCOBJs[createdItem.FormKey].Add(cobj.FormKey);
            }

            // Second pass: items with tempering recipes but no crafting recipe (uniques/artifacts).
            // Study mechanic is identical — player must hold the item at a bench.
            Console.WriteLine("Finding temperable items without crafting recipes (uniques/artifacts)...");
            foreach (var (itemFormKey, _) in temperCOBJsCache)
            {
                if (itemCOBJs.ContainsKey(itemFormKey))
                    continue;

                if (!state.LinkCache.TryResolve<IItemGetter>(itemFormKey, out var uncraftableItem))
                    continue;

                if (settings.itemBlacklist.Contains(uncraftableItem))
                    continue;

                itemCOBJs[itemFormKey] = new List<FormKey>();
            }

            Console.WriteLine($"Found {itemCOBJs.Count} items total. Creating mastery records...");
            Console.WriteLine(string.Empty);

            // Create the 4 parallel FormLists
            var trackedItemsList = state.PatchMod.FormLists.AddNew();
            trackedItemsList.EditorID = "HEP_TrackedItems";

            var masteryPerksList = state.PatchMod.FormLists.AddNew();
            masteryPerksList.EditorID = "HEP_MasteryPerks";

            var progressGlobalsList = state.PatchMod.FormLists.AddNew();
            progressGlobalsList.EditorID = "HEP_ProgressGlobals";

            var thresholdGlobalsList = state.PatchMod.FormLists.AddNew();
            thresholdGlobalsList.EditorID = "HEP_ThresholdGlobals";

            // Process each item
            foreach (var (createdItemFormKey, cobjFormKeys) in itemCOBJs)
            {
                if (
                    !state.LinkCache.TryResolve<IItemGetter>(createdItemFormKey, out var createdItem)
                    || createdItem is not INamedGetter createdItemName
                    || createdItem is not IKeywordedGetter createdItemKeywords
                )
                    continue;

                string? objName = createdItemName.Name;
                string? objEditorID = createdItem.EditorID;

                if (string.IsNullOrEmpty(objName) || string.IsNullOrEmpty(objEditorID))
                    continue;

                // Faction keyword check
                bool isFactionItem =
                    settings.FactionKeywords.Count > 0
                    && createdItemKeywords.Keywords != null
                    && settings.FactionKeywords.Any(fkw =>
                        createdItemKeywords.Keywords.Any(kw => kw.FormKey == fkw.FormKey));

                if (isFactionItem && !lvliCache.ContainsKey(createdItemFormKey))
                {
                    // Not obtainable in the world — permanently hide from the crafting table
                    foreach (var craftingCobjFormKey in cobjFormKeys)
                    {
                        if (!state.LinkCache.TryResolve<IConstructibleObjectGetter>(
                            craftingCobjFormKey, out var craftingCobj))
                            continue;
                        var modifiedCraftingCOBJ = state.PatchMod.ConstructibleObjects.GetOrAddAsOverride(craftingCobj);
                        if (!settings.KeepVanillaCraftingConditions)
                            modifiedCraftingCOBJ.Conditions.Clear();
                        var blockedPerk = state.PatchMod.Perks.AddNew();
                        blockedPerk.EditorID = $"HEP_FactionBlocked_{objEditorID}";
                        blockedPerk.Name = $"[Faction Locked] {objName}";
                        var blockCond = new HasPerkConditionData() { RunOnType = Condition.RunOnType.Subject };
                        blockCond.Perk = new FormLinkOrIndex<IPerkGetter>(blockCond, blockedPerk.FormKey);
                        blockCond.Perk.Link.SetTo(blockedPerk.FormKey);
                        modifiedCraftingCOBJ.Conditions.Add(new ConditionFloat()
                        {
                            ComparisonValue = 1,
                            CompareOperator = CompareOperator.GreaterThanOrEqualTo,
                            Data = blockCond,
                        });
                        if (settings.ShowDebugLogs)
                            Console.WriteLine($"  Faction locked (not in loot): {objName}");
                    }
                    continue;
                }
                // isFactionItem && in leveled lists: process normally but skip LVLI injection
                // so the only path to the schematic is looting a faction member and breaking it down

                if (settings.ShowDebugLogs)
                {
                    Console.WriteLine(string.Empty);
                    Console.WriteLine($"Processing {objName} ...");
                }
                else
                    Console.WriteLine($"Patching for {objName} ...");

                // Determine object type for threshold calculation
                string objType = "Misc";
                switch (createdItem)
                {
                    case IWeaponGetter:
                        objType = "Weapon";
                        break;
                    case IIngestibleGetter:
                        objType = "Cooking";
                        break;
                    case IArmorGetter armorObj:
                        switch (armorObj.BodyTemplate?.FirstPersonFlags)
                        {
                            case BipedObjectFlag.Amulet or BipedObjectFlag.Ring:
                                objType = "Jewelry";
                                break;
                            case BipedObjectFlag.Head:
                                objType = "Helmet";
                                break;
                            default:
                                objType = "Armor";
                                break;
                        }
                        if (armorObj.EquipmentType.FormKey == Skyrim.EquipType.Shield.FormKey)
                            objType = "Shield";
                        break;
                }

                // Unique/artifact check: doubles the mastery threshold
                bool isUnique =
                    settings.UniqueItemList.Any(l => l.FormKey == createdItemFormKey)
                    || (
                        createdItemKeywords.Keywords != null
                        && settings.UniqueItemKeywords.Any(ukw =>
                            createdItemKeywords.Keywords.Any(kw => kw.FormKey == ukw.FormKey)
                        )
                    );

                float threshold = GenData.GetMasteryThreshold(createdItemKeywords, objType, isUnique);

                if (settings.ShowDebugLogs)
                    Console.WriteLine(
                        $"  Tier threshold: {threshold}{(isUnique ? " (unique ×2)" : string.Empty)}"
                    );

                // Mastery system: all items tracked for bench-visit tempering unlock
                var masteryPerk = state.PatchMod.Perks.AddNew();
                masteryPerk.EditorID = $"HEP_Mastered_{objEditorID}";
                masteryPerk.Name = $"Mastered: {objName}";

                var progressGlobal = new GlobalFloat(
                    state.PatchMod.GetNextFormKey(),
                    SkyrimRelease.SkyrimSE
                );
                progressGlobal.EditorID = $"HEP_Progress_{objEditorID}";
                progressGlobal.Data = 0.0f;
                state.PatchMod.Globals.Add(progressGlobal);

                var thresholdGlobal = new GlobalFloat(
                    state.PatchMod.GetNextFormKey(),
                    SkyrimRelease.SkyrimSE
                );
                thresholdGlobal.EditorID = $"HEP_Threshold_{objEditorID}";
                thresholdGlobal.Data = threshold;
                state.PatchMod.Globals.Add(thresholdGlobal);

                trackedItemsList.Items.Add(
                    new FormLink<ISkyrimMajorRecordGetter>(createdItemFormKey)
                );
                masteryPerksList.Items.Add(
                    new FormLink<ISkyrimMajorRecordGetter>(masteryPerk.FormKey)
                );
                progressGlobalsList.Items.Add(
                    new FormLink<ISkyrimMajorRecordGetter>(progressGlobal.FormKey)
                );
                thresholdGlobalsList.Items.Add(
                    new FormLink<ISkyrimMajorRecordGetter>(thresholdGlobal.FormKey)
                );

                // Crafting gate: craftable items also require schematic unlock before tempering
                Perk? craftingUnlockPerk = null;

                if (cobjFormKeys.Count > 0)
                {
                    int complexity = GenData.GetSchematicComplexity(createdItem, createdItemKeywords, objType);

                    if (settings.ShowDebugLogs)
                        Console.WriteLine($"  Crafting complexity: {complexity} schematics required");

                    // Create crafting unlock perk (condition flag on crafting COBJs)
                    var craftingPerk = state.PatchMod.Perks.AddNew();
                    craftingPerk.EditorID = $"HEP_CraftingUnlocked_{objEditorID}";
                    craftingPerk.Name = $"Recipe: {objName}";

                    // Create crafting progress global (counts schematics studied)
                    var craftingProgress = new GlobalFloat(
                        state.PatchMod.GetNextFormKey(),
                        SkyrimRelease.SkyrimSE
                    );
                    craftingProgress.EditorID = $"HEP_CraftingProgress_{objEditorID}";
                    craftingProgress.Data = 0.0f;
                    state.PatchMod.Globals.Add(craftingProgress);

                    // Create crafting threshold global (stores complexity score 2–11)
                    var craftingThreshold = new GlobalFloat(
                        state.PatchMod.GetNextFormKey(),
                        SkyrimRelease.SkyrimSE
                    );
                    craftingThreshold.EditorID = $"HEP_CraftingThreshold_{objEditorID}";
                    craftingThreshold.Data = (float)complexity;
                    state.PatchMod.Globals.Add(craftingThreshold);

                    // Create schematic book with script properties
                    var schematicBook = state.PatchMod.Books.AddNew();
                    schematicBook.EditorID = $"HEP_Schematic_{objEditorID}";
                    schematicBook.Name = $"Schematic: {objName}";

                    var bookAdapter = new VirtualMachineAdapter();
                    var schematicScript = new ScriptEntry();
                    schematicScript.Name = "HEP_SchematicScript";
                    schematicScript.Properties.Add(new ScriptObjectProperty()
                    {
                        Name = "HEP_CraftingProgress",
                        Object = new FormLink<ISkyrimMajorRecordGetter>(craftingProgress.FormKey),
                    });
                    schematicScript.Properties.Add(new ScriptObjectProperty()
                    {
                        Name = "HEP_CraftingThreshold",
                        Object = new FormLink<ISkyrimMajorRecordGetter>(craftingThreshold.FormKey),
                    });
                    schematicScript.Properties.Add(new ScriptObjectProperty()
                    {
                        Name = "HEP_CraftingUnlockedPerk",
                        Object = new FormLink<ISkyrimMajorRecordGetter>(craftingPerk.FormKey),
                    });
                    bookAdapter.Scripts.Add(schematicScript);
                    schematicBook.VirtualMachineAdapter = bookAdapter;

                    // Breakdown COBJ: 1× base item at smelter → 1× schematic
                    var breakdownCOBJ = state.PatchMod.ConstructibleObjects.AddNew();
                    breakdownCOBJ.EditorID = $"HEP_Breakdown_{objEditorID}";
                    breakdownCOBJ.WorkbenchKeyword.SetTo(
                        objType == "Cooking"
                            ? Skyrim.Keyword.CraftingCookpot
                            : Skyrim.Keyword.CraftingSmelter
                    );
                    breakdownCOBJ.CreatedObject.SetTo(schematicBook);
                    breakdownCOBJ.CreatedObjectCount = 1;
                    breakdownCOBJ.Items ??= new();
                    breakdownCOBJ.Items.Add(new ContainerEntry()
                    {
                        Item = new ContainerItem()
                        {
                            Item = new FormLink<IItemGetter>(createdItemFormKey),
                            Count = 1,
                        }
                    });

                    // Patch crafting COBJs to require the unlock perk
                    foreach (var craftingCobjFormKey in cobjFormKeys)
                    {
                        if (!state.LinkCache.TryResolve<IConstructibleObjectGetter>(
                            craftingCobjFormKey, out var craftingCobj))
                            continue;

                        var modifiedCraftingCOBJ = state.PatchMod.ConstructibleObjects.GetOrAddAsOverride(craftingCobj);
                        if (!settings.KeepVanillaCraftingConditions)
                            modifiedCraftingCOBJ.Conditions.Clear();
                        var craftingPerkCond = new HasPerkConditionData()
                        {
                            RunOnType = Condition.RunOnType.Subject,
                        };
                        craftingPerkCond.Perk = new FormLinkOrIndex<IPerkGetter>(
                            craftingPerkCond, craftingPerk.FormKey
                        );
                        craftingPerkCond.Perk.Link.SetTo(craftingPerk.FormKey);
                        modifiedCraftingCOBJ.Conditions.Add(new ConditionFloat()
                        {
                            ComparisonValue = 1,
                            CompareOperator = CompareOperator.GreaterThanOrEqualTo,
                            Data = craftingPerkCond,
                        });

                        if (settings.ShowDebugLogs)
                            Console.WriteLine($"  Patched crafting COBJ: {craftingCobj.EditorID}");
                    }

                    // LVLI injection: skipped for faction items — breakdown is the only unlock path
                    if (!isFactionItem && lvliCache.TryGetValue(createdItemFormKey, out var containingLvlis))
                    {
                        foreach (var lvli in containingLvlis)
                        {
                            if (lvli.Entries == null) continue;
                            var newEntries = new List<LeveledItemEntry>();
                            foreach (var entry in lvli.Entries)
                            {
                                if (entry.Data?.Reference.FormKey != createdItemFormKey) continue;
                                newEntries.Add(new LeveledItemEntry()
                                {
                                    Data = new LeveledItemEntryData()
                                    {
                                        Reference = new FormLink<IItemGetter>(schematicBook.FormKey),
                                        Level = entry.Data.Level,
                                        Count = 1,
                                    }
                                });
                            }
                            if (newEntries.Count == 0) continue;
                            var modifiedLvli = state.PatchMod.LeveledItems.GetOrAddAsOverride(lvli);
                            foreach (var e in newEntries)
                                modifiedLvli.Entries!.Add(e);
                        }
                    }

                    craftingUnlockPerk = craftingPerk;
                }

                // Patch tempering COBJs to require the tempering gate perk
                if (
                    !temperCOBJsCache.TryGetValue(createdItemFormKey, out var temperCOBJs)
                )
                    continue;

                foreach (var temperCOBJ in temperCOBJs)
                {
                    var modifiedTemperCOBJ = state.PatchMod.ConstructibleObjects.GetOrAddAsOverride(
                        temperCOBJ
                    );

                    // Blacksmith tutorial workaround: tutorial quest stage bypasses mastery req
                    if (
                        temperCOBJ.FormKey
                            == Skyrim.ConstructibleObject.TemperWeaponIronDagger.FormKey
                        || temperCOBJ.FormKey
                            == Skyrim.ConstructibleObject.TemperArmorHideHelmet.FormKey
                    )
                    {
                        var tutorialCond = new GetStageConditionData();
                        tutorialCond.Quest = new FormLinkOrIndex<IQuestGetter>(
                            tutorialCond,
                            Skyrim.Quest.TutorialBlacksmithing.FormKey
                        );
                        tutorialCond.Quest.Link.SetTo(Skyrim.Quest.TutorialBlacksmithing.FormKey);
                        modifiedTemperCOBJ.Conditions.Add(
                            new ConditionFloat()
                            {
                                ComparisonValue =
                                    temperCOBJ.FormKey
                                    == Skyrim.ConstructibleObject.TemperArmorHideHelmet.FormKey
                                        ? 90
                                        : 30,
                                CompareOperator = CompareOperator.GreaterThanOrEqualTo,
                                Data = tutorialCond,
                                Flags = Condition.Flag.OR
                            }
                        );
                    }

                    // Craftable items: also require crafting unlock before tempering
                    if (craftingUnlockPerk != null)
                    {
                        var craftingGateCond = new HasPerkConditionData()
                        {
                            RunOnType = Condition.RunOnType.Subject,
                        };
                        craftingGateCond.Perk = new FormLinkOrIndex<IPerkGetter>(
                            craftingGateCond, craftingUnlockPerk.FormKey
                        );
                        craftingGateCond.Perk.Link.SetTo(craftingUnlockPerk.FormKey);
                        modifiedTemperCOBJ.Conditions.Add(new ConditionFloat()
                        {
                            ComparisonValue = 1,
                            CompareOperator = CompareOperator.GreaterThanOrEqualTo,
                            Data = craftingGateCond,
                        });
                    }

                    // All items: require mastery perk to temper
                    var perkCondData = new HasPerkConditionData()
                    {
                        RunOnType = Condition.RunOnType.Subject,
                    };
                    perkCondData.Perk = new FormLinkOrIndex<IPerkGetter>(
                        perkCondData,
                        masteryPerk.FormKey
                    );
                    perkCondData.Perk.Link.SetTo(masteryPerk.FormKey);

                    modifiedTemperCOBJ.Conditions.Add(
                        new ConditionFloat()
                        {
                            ComparisonValue = 1,
                            CompareOperator = CompareOperator.GreaterThanOrEqualTo,
                            Data = perkCondData,
                        }
                    );

                    if (settings.ShowDebugLogs)
                        Console.WriteLine($"  Patched tempering COBJ: {temperCOBJ.EditorID}");
                }
            }

            Console.WriteLine(string.Empty);
            Console.WriteLine("Creating mastery quest and player alias...");

            // Create auto-start quest running HEP_PlayerAlias as a quest-level script
            var quest = state.PatchMod.Quests.AddNew();
            quest.EditorID = "HEP_MasteryQuest";
            quest.Name = "Hephaestus Mastery Tracker";
            // NOTE: quest.StartGameEnabled cannot be set via Mutagen 0.41 public API.
            // Open the output ESP in SSEEdit and check "Start Game Enabled" on HEP_MasteryQuest manually.
            quest.Priority = 0;

            // Build the quest-level script entry with FormList + player properties
            var questScriptEntry = new ScriptEntry();
            questScriptEntry.Name = "HEP_PlayerAlias";
            questScriptEntry.Properties.Add(
                new ScriptObjectProperty()
                {
                    Name = "HEP_TrackedItems",
                    Object = new FormLink<ISkyrimMajorRecordGetter>(trackedItemsList.FormKey),
                }
            );
            questScriptEntry.Properties.Add(
                new ScriptObjectProperty()
                {
                    Name = "HEP_MasteryPerks",
                    Object = new FormLink<ISkyrimMajorRecordGetter>(masteryPerksList.FormKey),
                }
            );
            questScriptEntry.Properties.Add(
                new ScriptObjectProperty()
                {
                    Name = "HEP_ProgressGlobals",
                    Object = new FormLink<ISkyrimMajorRecordGetter>(progressGlobalsList.FormKey),
                }
            );
            questScriptEntry.Properties.Add(
                new ScriptObjectProperty()
                {
                    Name = "HEP_ThresholdGlobals",
                    Object = new FormLink<ISkyrimMajorRecordGetter>(thresholdGlobalsList.FormKey),
                }
            );
            questScriptEntry.Properties.Add(
                new ScriptObjectProperty()
                {
                    Name = "PlayerRef",
                    Object = new FormLink<ISkyrimMajorRecordGetter>(Skyrim.Npc.Player.FormKey),
                }
            );

            var questAdapter = new QuestAdapter();
            questAdapter.Scripts.Add(questScriptEntry);
            quest.VirtualMachineAdapter = questAdapter;

            Console.WriteLine(string.Empty);
            Console.WriteLine("=================================================");
            Console.WriteLine(
                $"Done. Created mastery records for {itemCOBJs.Count} items."
            );
            Console.WriteLine(string.Empty);
            Console.WriteLine("POST-PATCHER STEPS REQUIRED:");
            Console.WriteLine(
                "  1. Open Hephaestus.esp in SSEEdit, find HEP_MasteryQuest,"
            );
            Console.WriteLine(
                "     and check the 'Start Game Enabled' flag so the quest auto-starts."
            );
            Console.WriteLine("=================================================");
        }
    }
}
